### ISSUE TITLE
ModLoader crashes when Steam is already running

### ISSUE THREAD

**Issue by manuel3108** [bdgmb2/aceo-modloader#1]
When you start the modLoader one time, everything works well, When the ML was executed one time, ML crashes (the console window closes) when the settings window of ACEO appears.

But the changes to the assambly are done, because I am able to see, that the mods are loaded. I have tried a bit around in the code, but i dont have found a solution. Maybe we you should start to processes, one for Steam and another for ACEO

**Comment by bdgmb2** [comment]
I unfortunately cannot reproduce on my machine, but I did push a commit that hopefully will stop ModLoader from crashing instantly... in your case I bet it's throwing an exception. Can you pull the latest commit and try running it again? Hopefully the console will tell you the exception message.

**Comment by manuel3108** [comment]
Mhm, actually I am not able to reproduce it, also when the code has not really changed. I dont't know what the problem was yesterday

**Comment by bdgmb2** [comment]
Ok. Reopen if it happens again.

**Comment by manuel3108** [comment]
Yes, I will do.
